spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ssuk_ssuk?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    #url: jdbc:mysql://localhost:3306/ssuk_ssuk?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    username: ssafy
#    password: b102ssuk

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ssukssuk102
#    password: bodxihtuxhwrzcfb
#    properties:
#      mail:
#        smtp:
#          auth: true
#          timeout: 5000
#          starttls:
#            enable: true

  redis:
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
    host: localhost
    port: 6379

  jpa:
    database: mysql   # 추가 해준 부분
    open-in-view: true
    hibernate:
      ddl-auto: none
      #ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
#    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  config:
    import:
      - port.yml
      - cloud.yml
      - db.yml
      - email.yml
      - jwt.yml

logging:
  level:
#    root: debug
    org.hibernate.SQL: debug
    # 일단 ssuk패키지 debug로 설정해놓을게요
    com.ssafy.ssuk: debug

#jwt:
#  secret: 6YCyHl8E+3j0FHz13dF4lNU6YFLx/8ZKdo/Z0rZzGps=

